### ISSUE TITLE
PineTab (aka Quirky Devices)

### ISSUE THREAD

**Issue by zhaofengli** [efernau/rot8#15]
So I recently got a [PineTab](https://wiki.pine64.org/index.php/PineTab), which is an ARM tablet with a detachable keyboard dock (see picture, the magnetic connector is actually USB). It has the following quirks:

## The *native orientation* is rotated by 90 degrees

![my-neck-hurts](https://user-images.githubusercontent.com/2189609/92981914-d10be480-f450-11ea-9cd6-30ad06b17704.jpg)

(Yes, that's the native resolution - 800x1280)

Because we use the `normal` orientation to decide whether to enable the keyboard, we need to

- a) allow the user to specify "the orientation at which the keyboard is disabled" - easy but confusing ("why is my normal not 'normal'?"), or
- b) allow the user to specify a rotation applied to the vector before deciding the orientation - less confusing

Actually, as the keyboard can be detached, we should have a feature where we lock the rotation to the normal *human orientation* when an input device is present (in this case, the USB keyboard).

Edit: Wanted to set up everything again half a year later, and saw this silliness. Please, ignore my brain fart :laughing: There is no need to normalize anything, or flip the axes. In fact, the current code in `src/main.rs` is over-complicating the thing by comparing the vectors.

**Comment by zhaofengli** [comment]
Still WIP, but I've made some changes to accommodate PineTab and similar devices.

**Comment by zhaofengli** [comment]
Still WIP, but I've made some changes to accommodate PineTab and similar devices:

* Use the correct accelerometer value scale

Not all devices have the accelerometer raw values between 0 and 1 (e.g. PineTab). The correct scale is accessible via sysfs.

* Revamped keyboard mode system

I added `--keyboard-mode`, which can be one of:

- `integrated`: The keyboard is an integral part of the device. We will disable the keyboard when the screen is not oriented upright.
- `detachable`: The keyboard is detachable. We will keep the screen oriented upright when the keyboard is attached.
- `none`: We won't touch your keyboard.

* After-rotation hook (#4)

You can specify a command to be run in shell after rotation with `--rotate-hook`. Useful for forcing a restart of Polybar, for example.

**Comment by thurstylark** [comment]
I also have issues with the accelerometer value scale. For my hw, `/sys/bus/iio/devices/iio\:device0/in_accel_scale` contains `0.009806650`

I believe all that's necessary is to replace `/ 1e6` with a multiplication of whatever value is read from `in_accel_scale`:

https://github.com/efernau/rot8/blob/b7b42d95a99996215ae31bddcd70af3c34c165f6/src/main.rs#L260-L262
