### ISSUE TITLE
Not rotating with sway on Surface 3 (non pro) - DSI-1 

### ISSUE THREAD

**Issue by abondis** [efernau/rot8#16]
I tried to use rot8 on a Surface 3 which has a screen shown as DSI-1, instead of the default eDP1.

Using `-d DSI-1` doesn't seem to do anything. Just in case, I tried as root, but still no luck.
On another tablet, non surface and with eDP1 screen, rot8 works perfectly, so I'm hoping to get the same experience with the surface :)

Is there a way to debug or get logs?

Rotation from gdm or in gnome, without rot8, works properly so I guess the sensors are fine.

**Comment by juanbono** [comment]
I think you have tweak a bit the normalization-factor (1e3 worked for me). Also I had to pass the `--xy` arg with value= `yx`.
The end result was something like this:
```rot8 -d DSI-1 --normalization-factor 1e3 --xy yx```

**Comment by juanbono** [comment]
One way to debug the normalization factor is to print the variable `d` here https://github.com/efernau/rot8/blob/88f5bda28b8cc0b7af5a190b84c08cdc557bbf7c/src/main.rs#L344 and see its value. A really high value (or really low) can mean that you have to tweak a bit the normalization factor. Take into account that later it is compared to the threshold (0.5 by default) so the comparison "should make sense". For example, `d` should not be a number like 12900. You can change it to 0.129 changing the normalization factor.

**Comment by abondis** [comment]
Thank you for the details.

I won't be able to test/confirm anytime soon as I don't have access to the tablet for now.

Aug. 1, 2022 9:17:41 a.m. Juan Bono ***@***.***>:
