### ISSUE TITLE
Panic on backend

### ISSUE THREAD

**Issue by phodina** [efernau/rot8#19]
Hi,
thanks for awesome crate. However, I ran it on my desktop machine with GDM running under X11 and I got panic. Seems there are some `unwrap` calls when querying the backend.

FYI I'm [packaging](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=49703) this crate for [Guix](https://guix.gnu.org/en/about/).

```
$ RUST_BACKTRACE=1 /gnu/store/rwbscw79gmc5bn1zdxxkwjszfpgzmqsh-rust-rot8-0.1.3/bin/rot8 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:134:40
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: rot8::main
  10: std::rt::lang_start::{{closure}}
  11: std::rt::lang_start_internal
  12: main
  13: __libc_start_main
  14: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by efernau** [comment]
Hi,

thanks for the Guix package!

Can't reproduce your error at the moment. 
The error points to an unwrap at line 134, here we do a "pidof sway" command. Is this the problem? But the error text ```NotFound, message: "No such file or directory"``` makes me think otherwise.
Do you have an accelerometer device with path "/sys/bus/iio/devices/iio:device*/in_accel_*_raw"?

**Comment by efernau** [comment]
Hey,

normally the accelerometer are exposed in the sys file system, exported via the /sys directory.

Each sensor device is exposed as a subdirectory of /sys/bus/iio/devices with a name following the scheme iio:device<n> where <n> is the numeric index of the device.

Are you sure you have an accelerometer? 
which kernel do you use `uname -r`
Do you have IIO module in your kernel? 
Maybe this helps: [Linux kernel sysfs IIO devices](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/ABI/testing/sysfs-bus-iio)
Maybe you need a packet like this: `iio-sensor-proxy`

**Comment by Duccy8502** [comment]
No, I'm not sure that I have an accelerometer but I do know that previous releases of this laptop do include one. I'm using 5.18.9, the Void build is called 5.18.9_1. Using `lsmod` and `cat /proc/modules`, it does not appear that I have the iio module enabled. Going to try `iio-sensor-proxy` and enable the module. I'll update with the result.
