### ISSUE TITLE
Can't set touchscreen

### ISSUE THREAD

**Issue by ngharrison** [efernau/rot8#38]
I just installed rot8 through the rot8-git AUR package. Upon trying `rot8 --touchscreen "ELAN9008:00 04F3:2C82"`, ~~it hangs and never finishes~~ it doesn't rotate the screen (I misunderstood). Is there something I'm missing?

**Comment by xnghu** [comment]
I am experiencing the same thing, will let you know if I find out anything / get it to work

**Comment by xnghu** [comment]
@ngharrison I got it to work by getting the name for my touchscreen device with: `xinput list`

then running: `rot8 --touchscreen "<name of my touchscreen>" ` worked as expected

**Comment by ngharrison** [comment]
@xnghu  Yes, that's what I did as well. I'm not 100% sure that I've picked the right one though since none of them say anything about a screen. My output from `xinput list`:

> ⎡ Virtual core pointer                          id=2    [master pointer  (3)]
> ⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
> ⎜   ↳ Asus Keyboard                             id=10   [slave  pointer  (2)]
> ⎜   ↳ Asus Keyboard                             id=12   [slave  pointer  (2)]
> ⎜   ↳ ELAN9008:00 04F3:2C82                     id=14   [slave  pointer  (2)]
> ⎜   ↳ ELAN1201:00 04F3:3098 Mouse               id=16   [slave  pointer  (2)]
> ⎜   ↳ ELAN1201:00 04F3:3098 Touchpad            id=17   [slave  pointer  (2)]
> ⎜   ↳ Asus Keyboard                             id=19   [slave  pointer  (2)]
> ⎜   ↳ ELAN9008:00 04F3:2C82 Stylus Pen (0)      id=23   [slave  pointer  (2)]
> ⎜   ↳ ELAN9008:00 04F3:2C82 Stylus Eraser (0)   id=24   [slave  pointer  (2)]
> ⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
>     ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
>     ↳ Video Bus                                 id=6    [slave  keyboard (3)]
>     ↳ Lid Switch                                id=7    [slave  keyboard (3)]
>     ↳ Power Button                              id=8    [slave  keyboard (3)]
>     ↳ Sleep Button                              id=9    [slave  keyboard (3)]
>     ↳ Asus Keyboard                             id=11   [slave  keyboard (3)]
>     ↳ USB2.0 HD UVC WebCam: USB2.0 HD           id=13   [slave  keyboard (3)]
>     ↳ ELAN9008:00 04F3:2C82 Stylus              id=15   [slave  keyboard (3)]
>     ↳ Asus WMI hotkeys                          id=18   [slave  keyboard (3)]
>     ↳ Asus Keyboard                             id=20   [slave  keyboard (3)]
>     ↳ Asus Keyboard                             id=21   [slave  keyboard (3)]
>     ↳ Asus Keyboard                             id=22   [slave  keyboard (3)]

**Comment by ngharrison** [comment]
With the new update giving a useful error message and looking into the code, I found that I my accelerometer can't be found. Somehow my entire /sys/bus/iio/ directory disappeared. I know it existed before because I had a different auto-rotate package working a week ago. Not sure how to get it back, but this issue is resolved.

**Comment by ngharrison** [comment]
I've fixed my accelerometer problem -- the /sys/bus/iio/ directory exists again and I can monitor rotation changes using monitor-sensor in `iio-sensor-proxy`. But auto-rotate still doesn't work. Am I doing something wrong with the name? I checked using `udevadm info --export-db` and "ELAN9008:00 04F3:2C82" has ID_INPUT_TOUCHSCREEN=1. I also tested it with all other possible names listed in `xinput list` for fun but no change.

The command I'm using: `rot8 --toucscreen "ELAN9008:00 04F3:2C82"

**Comment by ngharrison** [comment]
The name I was using for the touchscreen was correct. In the end, it wasn't working because the values weren't normalized appropriately for my machine. Mine needed `rot8 --normalization-factor 10 --touchscreen "ELAN9008:00 04F3:2C82"`. This is resolved.
