### ISSUE TITLE
Consider the wlr-output-management protocol over swaymsg

### ISSUE THREAD

**Issue by ddevault** [efernau/rot8#5]
https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-output-management-unstable-v1.xml

**Comment by Estebiu** [comment]
A more general solution would also suit my needs much better; as I'm using hyprland for the moment. I would love to get rot8 to work on it.

**Comment by Smona** [comment]
I've been working on a change that will switch to the output management protocol in all wlroots environments. I have it working now on both sway and hyprland, after resolving [an upstream issue](https://github.com/hyprwm/Hyprland/issues/3220) in the latter. I'm pretty new to rust so I'm just double checking my design choices at the moment, but I should be able to get a PR up in the next couple of weeks.

**Comment by efernau** [comment]
Awesome! Exciting to hear about your progress with wayland support. 
Looking forward to your PR in the next few weeks! 🦀
