### ISSUE TITLE
configuration clarification

### ISSUE THREAD

**Issue by scurrvy2020** [efernau/rot8#6]
I'm using sway and I'm not able to get this to work 

Which input am I supposed to map to which output?  Is it the accelerometer to the display? or touchpad to the display?

If I call 'rot8 --display DSI-1' it also does not appear to work.

**Comment by deadly-platypus** [comment]
I'm also confused, as it works when I run it in a terminal, but doesn't when I put `exec rot8` in my sway config.

**Comment by rokyfox** [comment]
It's the touchscreen to the display. For example:
swaymsg input "1386:18669:Wacom_HID_48ED_Finger" map_to_output eDP-1
or
swaymsg input "1739:52602:00304238304C4C44:00_06CB:CD7A_Touchpad" map_to_output eDP-1
