### ISSUE TITLE
how rotate screen 90% before applying other factors?

### ISSUE THREAD

**Issue by Quackdoc** [efernau/rot8#96]
Some displays are set up vertically which gets really funky with x11. Plasma mobile seems to treat this fine, but under any x11 compositor. I have tried inverting x y and z but nothing seems to work. 

When I have my device in landscape orientation, x11 is in portrait mode and when I have it in portrait orientation, it becomes landscape mode. none of the combinations of "invert" seem to work either.

**Comment by efernau** [comment]
does ‘--invert-x’ not work for you?

**Comment by Quackdoc** [comment]
unfortunately it does not, I have a chuwi hi10x, if there are any logs or readings I can grab that would help I can do so.

**Comment by Quackdoc** [comment]
ohhhh, I looked through the applications help, you may want to update the readme as --invert-xy <xy> is not on it. Though granted, I probably should have checked both myself.
